Repository lamdacodex/Lapser, pull requests merged in 2024-10, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#9 updated README.md. fix #6
  .DS_Store
  README.md
Labels: documentation, hacktoberfest-accepted

#10 Password is hash and then saved into database
  .DS_Store
  primary-backend/package-lock.json
  primary-backend/package.json
  primary-backend/src/router/user.ts
  primary-backend/yarn.lock
Labels: bug, hacktoberfest-accepted

#12 Added a testing route
  primary-backend/src/index.ts
Labels: enhancement, good first issue, hacktoberfest-accepted

#13 Added a send sol and webhook route
  worker/src/index.ts
Labels: bug, enhancement, hacktoberfest-accepted
